#include <stdio.h>

/*
Even Fibonacci numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

int main(void)
{   
    int a = 1;
    int b = 2;
    int sum = 0;
    int allsum = 0;

    while (a <= 4000000)
    {
        sum = b + a;
        if (a % 2 == 0)
            allsum += a;
        a = b;
        b = sum;
        sum = 0;
    }
    printf("%d\n",allsum);

    return 0;
} 